#macro VIEW 0
#macro VIEW_CAM view_camera[VIEW]
#macro VIEW_WIDTH 480
#macro VIEW_HEIGHT 270
#macro VIEW_SCALE 3

#macro GUI_WIDTH VIEW_WIDTH
#macro GUI_HEIGHT VIEW_HEIGHT

#macro WINDOW_TITLE "None Jam 8"
#macro WINDOW_WIDTH VIEW_WIDTH * VIEW_SCALE
#macro WINDOW_HEIGHT VIEW_HEIGHT * VIEW_SCALE